test6/Controllers/IssueController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using test6.Data;
using test6.Models;

namespace test6.Controllers
{
    [Authorize(Roles = "Admin,Developer")]
    public class IssueController : Controller
    {
        private readonly ApplicationDbContext _db;

        public IssueController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Issue> objList = _db.Issue;
            return View(objList);
        }
        //GET-CREATE
        public IActionResult Create()
        {
            return View();
        }
        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Issue obj)
        {
            _db.Issue.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
       
        //GET-EDIT
        public IActionResult Edit(string ProjectName)
        {
            if (ProjectName == null)
            {
                return NotFound();
            }
            var obj = _db.Issue.Find(ProjectName);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //POST-EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Issue obj)
        {
            _db.Issue.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

test6/Controllers/ManageRolesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using test6.Models;
using test6.Data;
using Microsoft.AspNetCore.Authorization;

namespace test6.Controllers
{
    [Authorize(Roles="Admin,Developer")]
    public class ManageRolesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ManageRolesController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<ManageRoles> objList = _db.ManageRoles;
            return View(objList);
        }
        //GET-CREATE
        public IActionResult Create()
        {
            return View();
        }
        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ManageRoles obj)
        {
            _db.ManageRoles.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        //GET-EDIT
        public IActionResult Edit(string Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var obj = _db.ManageRoles.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //POST-EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ManageRoles obj)
        {
            _db.ManageRoles.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        //GET-DELETE
        public IActionResult Delete(string Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var obj = _db.ManageRoles.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //POST-DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(string Id)
        {
            var obj = _db.ManageRoles.Find(Id);
            _db.ManageRoles.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

test6/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using test6.Data;
using test6.Models;

namespace test6.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ProjectsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Projects> objList = _db.Projects;
            return View(objList);
        }
        //GET-CREATE
        public IActionResult Create()
        {
            return View();
        }
        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Projects obj)
        {
            _db.Projects.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        //GET-EDIT
        public IActionResult Edit(string Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var obj = _db.Projects.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //POST-EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Projects obj)
        {
            _db.Projects.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        //GET-DELETE
        public IActionResult Delete(string Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var obj = _db.Projects.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //POST-DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(string Id)
        {
            var obj = _db.Projects.Find(Id);
            _db.Projects.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

test6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - test6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css"   />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-bug"></i> &nbsp; Bug Tracker
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.IsInRole(WC.AdminRole))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ManageRoles" asp-action="Index">Manage Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Issue" asp-action="Index">Issues</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create New Admin</a>
                            </li>
                        }
                        else
                        {


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Issue" asp-action="Index">Issues</a>
                            </li>

                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - test6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>